import { type Product, type Collection, type Review } from "@/types";

// ─── Demo Collections ────────────────────────────────────

export const DEMO_COLLECTIONS: Collection[] = [
  {
    id: "col-1",
    name: "Meme Collection",
    slug: "meme",
    description: "The internet's greatest hits, now wearable. From classic memes to viral moments.",
    image: "/images/collections/meme.jpg",
    type: "MEME",
    featured: true,
    productCount: 24,
  },
  {
    id: "col-2",
    name: "Anime Drop",
    slug: "anime",
    description: "Wear your favorite anime. Premium prints of iconic characters and scenes.",
    image: "/images/collections/anime.jpg",
    type: "ANIME",
    featured: true,
    productCount: 18,
  },
  {
    id: "col-3",
    name: "Oversized Essentials",
    slug: "oversized",
    description: "Relaxed fits, premium fabric. The oversized silhouettes you've been looking for.",
    image: "/images/collections/oversized.jpg",
    type: "OVERSIZED",
    featured: true,
    productCount: 15,
  },
  {
    id: "col-4",
    name: "Trending Drops",
    slug: "trending",
    description: "What's hot right now. Limited quantities, unlimited drip.",
    image: "/images/collections/trending.jpg",
    type: "TRENDING",
    featured: true,
    productCount: 12,
  },
  {
    id: "col-5",
    name: "Limited Edition",
    slug: "limited",
    description: "Once they're gone, they're gone forever. Exclusive drops for the bold.",
    image: "/images/collections/limited.jpg",
    type: "LIMITED",
    featured: true,
    productCount: 8,
  },
];

// ─── Demo Products ───────────────────────────────────────

export const DEMO_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    name: "This Is Fine Oversized Tee",
    slug: "this-is-fine-oversized-tee",
    description: "The iconic 'This Is Fine' meme, reimagined in premium streetwear. Oversized fit with HD DTF print on 280GSM cotton.",
    shortDesc: "Classic meme meets premium streetwear",
    price: 2490,
    salePrice: 1990,
    images: ["/images/products/this-is-fine-1.jpg", "/images/products/this-is-fine-1.jpg"],
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: ["#0a0a0a", "#fafafa"],
    stockBySize: { S: 10, M: 15, L: 20, XL: 8, "2XL": 5 },
    totalStock: 58,
    categoryId: "cat-1",
    collectionId: "col-1",
    featured: true,
    trending: true,
    isNew: true,
    published: true,
    tags: ["meme", "oversized", "trending", "this-is-fine"],
    averageRating: 4.8,
    reviewCount: 127,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "prod-2",
    name: "Gojo Infinity Anime Tee",
    slug: "gojo-infinity-anime-tee",
    description: "Channel the strongest sorcerer. Premium anime-inspired design with metallic accents on heavyweight cotton.",
    shortDesc: "Jujutsu Kaisen inspired premium tee",
    price: 2790,
    images: ["/images/products/gojo-1.jpg", "/images/products/gojo-1.jpg"],
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: ["#0a0a0a", "#1a1a2e"],
    stockBySize: { S: 8, M: 12, L: 15, XL: 10, "2XL": 4 },
    totalStock: 49,
    categoryId: "cat-2",
    collectionId: "col-2",
    featured: true,
    trending: true,
    isNew: true,
    published: true,
    tags: ["anime", "jujutsu-kaisen", "gojo", "premium"],
    averageRating: 4.9,
    reviewCount: 89,
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
  },
  {
    id: "prod-3",
    name: "Sigma Grindset Tee",
    slug: "sigma-grindset-tee",
    description: "For the sigma males and females. Minimalist typography design on premium 240GSM cotton. The grindset is real.",
    shortDesc: "Minimalist sigma energy in premium cotton",
    price: 1990,
    images: ["/images/products/sigma-1.jpg", "/images/products/sigma-1.jpg"],
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: ["#0a0a0a"],
    stockBySize: { S: 12, M: 18, L: 22, XL: 10, "2XL": 6 },
    totalStock: 68,
    categoryId: "cat-1",
    collectionId: "col-1",
    featured: false,
    trending: true,
    isNew: false,
    published: true,
    tags: ["meme", "sigma", "typography", "minimalist"],
    averageRating: 4.7,
    reviewCount: 203,
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-10"),
  },
  {
    id: "prod-4",
    name: "Naruto Akatsuki Cloud Oversized",
    slug: "naruto-akatsuki-cloud-oversized",
    description: "Join the Akatsuki in style. Iconic red cloud pattern with distressed details. Drop-shoulder oversized fit on 280GSM cotton.",
    shortDesc: "Akatsuki vibes in oversized premium cotton",
    price: 2990,
    salePrice: 2490,
    images: ["/images/products/akatsuki-1.jpg", "/images/products/akatsuki-1.jpg"],
    sizes: ["M", "L", "XL", "2XL"],
    colors: ["#0a0a0a"],
    stockBySize: { M: 6, L: 8, XL: 5, "2XL": 3 },
    totalStock: 22,
    categoryId: "cat-2",
    collectionId: "col-2",
    featured: true,
    trending: false,
    isNew: true,
    published: true,
    tags: ["anime", "naruto", "akatsuki", "oversized", "limited"],
    averageRating: 4.9,
    reviewCount: 56,
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-02-01"),
  },
  {
    id: "prod-5",
    name: "404 Life Not Found Tee",
    slug: "404-life-not-found-tee",
    description: "Error: Life not found. A developer-culture classic with glitch art aesthetics. Perfect for coders and internet natives.",
    shortDesc: "Developer culture meets streetwear",
    price: 1790,
    images: ["/images/products/404-1.jpg", "/images/products/404-1.jpg"],
    sizes: ["S", "M", "L", "XL"],
    colors: ["#0a0a0a", "#1a1a2e"],
    stockBySize: { S: 15, M: 20, L: 25, XL: 12 },
    totalStock: 72,
    categoryId: "cat-1",
    collectionId: "col-4",
    featured: false,
    trending: true,
    isNew: false,
    published: true,
    tags: ["developer", "coding", "glitch", "internet-culture"],
    averageRating: 4.6,
    reviewCount: 167,
    createdAt: new Date("2024-01-05"),
    updatedAt: new Date("2024-01-05"),
  },
  {
    id: "prod-6",
    name: "Vintage Retro Wave Oversized",
    slug: "vintage-retro-wave-oversized",
    description: "Synthwave aesthetics meet streetwear. Neon gradient sunset with retro typography on oversized silhouette.",
    shortDesc: "Retro-futuristic vibes, premium oversized fit",
    price: 2690,
    images: ["/images/products/retrowave-1.jpg", "/images/products/retrowave-1.jpg"],
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: ["#0a0a0a"],
    stockBySize: { S: 5, M: 10, L: 12, XL: 8, "2XL": 4 },
    totalStock: 39,
    categoryId: "cat-3",
    collectionId: "col-3",
    featured: true,
    trending: false,
    isNew: true,
    published: true,
    tags: ["retro", "synthwave", "oversized", "neon", "aesthetic"],
    averageRating: 4.8,
    reviewCount: 42,
    createdAt: new Date("2024-02-10"),
    updatedAt: new Date("2024-02-10"),
  },
  {
    id: "prod-7",
    name: "Doge To The Moon Tee",
    slug: "doge-to-the-moon-tee",
    description: "Much wow. Very style. The legendary Doge meme in premium print quality. A must-have for every internet veteran.",
    shortDesc: "Such fashion. Very premium. Much wow.",
    price: 1990,
    salePrice: 1490,
    images: ["/images/products/doge-1.jpg", "/images/products/doge-1.jpg"],
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: ["#0a0a0a", "#fafafa"],
    stockBySize: { S: 20, M: 25, L: 30, XL: 15, "2XL": 8 },
    totalStock: 98,
    categoryId: "cat-1",
    collectionId: "col-1",
    featured: false,
    trending: false,
    isNew: false,
    published: true,
    tags: ["meme", "doge", "crypto", "classic"],
    averageRating: 4.5,
    reviewCount: 312,
    createdAt: new Date("2023-12-01"),
    updatedAt: new Date("2023-12-01"),
  },
  {
    id: "prod-8",
    name: "Attack On Titan Survey Corps",
    slug: "attack-on-titan-survey-corps",
    description: "Dedicate your heart. Survey Corps insignia with distressed military aesthetics. Heavyweight 300GSM limited edition.",
    shortDesc: "AoT Survey Corps limited edition heavyweight",
    price: 3290,
    images: ["/images/products/aot-1.jpg", "/images/products/aot-1.jpg"],
    sizes: ["M", "L", "XL"],
    colors: ["#0a0a0a"],
    stockBySize: { M: 3, L: 5, XL: 2 },
    totalStock: 10,
    categoryId: "cat-2",
    collectionId: "col-5",
    featured: true,
    trending: true,
    isNew: true,
    published: true,
    tags: ["anime", "aot", "attack-on-titan", "limited", "heavyweight"],
    averageRating: 5.0,
    reviewCount: 18,
    createdAt: new Date("2024-02-15"),
    updatedAt: new Date("2024-02-15"),
  },
];

// ─── Demo Reviews ────────────────────────────────────────

export const DEMO_REVIEWS: Review[] = [
  {
    id: "rev-1",
    userId: "user-1",
    userName: "Ahmed K.",
    productId: "prod-1",
    rating: 5,
    comment: "Bro the quality is insane!! 🔥 Way better than I expected. Print is super clear and the fabric is thick. Will order more.",
    images: [],
    verified: true,
    createdAt: new Date("2024-02-10"),
  },
  {
    id: "rev-2",
    userId: "user-2",
    userName: "Sara M.",
    productId: "prod-2",
    rating: 5,
    comment: "THE GOJO TEE IS EVERYTHING 😍 Perfect fit, amazing print quality. My friends are all jealous lol",
    images: [],
    verified: true,
    createdAt: new Date("2024-02-08"),
  },
  {
    id: "rev-3",
    userId: "user-3",
    userName: "Bilal A.",
    productId: "prod-3",
    rating: 4,
    comment: "Great quality shirt. Took 4 days to deliver to Lahore. The sigma design goes hard 💪",
    images: [],
    verified: true,
    createdAt: new Date("2024-02-05"),
  },
  {
    id: "rev-4",
    userId: "user-4",
    userName: "Fatima Z.",
    productId: "prod-4",
    rating: 5,
    comment: "Best anime tee I've ever bought in Pakistan!! The Akatsuki clouds look so sick. Oversized fit is perfect.",
    images: [],
    verified: true,
    createdAt: new Date("2024-02-01"),
  },
  {
    id: "rev-5",
    userId: "user-5",
    userName: "Hassan R.",
    productId: "prod-5",
    rating: 5,
    comment: "As a developer, I HAD to get this 😂 The glitch art is so clean. Material is premium for sure. 10/10",
    images: [],
    verified: true,
    createdAt: new Date("2024-01-28"),
  },
  {
    id: "rev-6",
    userId: "user-6",
    userName: "Ayesha T.",
    productId: "prod-6",
    rating: 5,
    comment: "The retro wave design is gorgeous! Got so many compliments. TrollFit is officially my fav brand 🫶",
    images: [],
    verified: true,
    createdAt: new Date("2024-01-25"),
  },
];
